title: Isom Lab
description: Code developed in the Isom Lab
theme: minima

header_pages:        # Only these pages will appear in the header
  - about.md       # Or whichever pages you actually want in the nav